version: '3.4'
services:
  web:
    build:
      context: .
      target: runner
    ports:
      - "5000:5000"
    volumes:
      - ./:/go/src/github.com/tkms0106/cloud-vision-text-detection-golang/
    env_file:
      - docker-compose.env.dec
